name:                flashblast
version:             0.0.9.0
git:                 https://gitlab.com/homotopic-tech/flashblast
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"
synopsis:            Generate language learning flashcards from video.

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DerivingVia
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLists
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- co-log-polysemy
- co-log-polysemy-formatting
- comonad
- composite-base
- dhall
- either
- extra
- first-class-families
- formatting
- generic-monoid
- http-conduit
- lucid
- megaparsec
- replace-megaparsec
- path
- path-dhall-instance
- path-utils
- polysemy
- polysemy-extra >= 0.1.4.0
- polysemy-fs
- polysemy-fskvstore
- polysemy-kvstore
- polysemy-http
- polysemy-log
- polysemy-methodology >= 0.1.6.0
- polysemy-methodology-composite >= 0.1.2.0
- polysemy-plugin
- polysemy-video >= 0.1.1.0
- polysemy-vinyl >= 0.1.2.0
- relude
- rio
- semialign
- optics
- optics-extra
- simple-media-timestamp
- srt
- srt-attoparsec
- text
- these
- unliftio-path
- vinyl

library:
  source-dirs: src

executables:
  flashblast:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flashblast

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fplugin=Polysemy.Plugin
