resolver: nightly-2021-08-03
packages:
- .
extra-deps:
- chronos-1.1.2
- co-log-0.4.0.1
- git: https://github.com/locallycompact/co-log-polysemy-formatting
  commit: 7a038aebd72747a4925492e46b131b7cb08dc977
- co-log-polysemy-0.0.1.2
- co-log-core-0.2.1.1
- git: https://github.com/locallycompact/composite
  commit: 7fa2ed8244f6d6c05081c8384338bb3ebffe03c3
  subdirs:
  - composite-base
- polysemy-conc-0.1.0.3
- polysemy-http-0.4.0.6
- polysemy-log-0.2.2.2
- polysemy-methodology-co-log-0.1.0.0
- polysemy-methodology-composite-0.1.4.0
- polysemy-time-0.1.3.1
- typerep-map-0.3.3.0
allow-newer: true
nix:
  packages: [zlib, libffi, ffmpeg, pkg-config, icu]
