resolver: nightly-2021-07-19
packages:
- .
extra-deps:
- chronos-1.1.2
- co-log-0.4.0.1
- git: https://github.com/locallycompact/co-log-polysemy-formatting
  commit: 7a038aebd72747a4925492e46b131b7cb08dc977
- co-log-polysemy-0.0.1.2
- co-log-core-0.2.1.1
- git: https://github.com/locallycompact/composite
  commit: 5644183439960e63d06ef8ec5e85c25356c6b1fc
  subdirs:
  - composite-base
- polysemy-conc-0.1.0.3
- polysemy-http-0.4.0.6
- polysemy-log-0.2.2.2
- polysemy-methodology-0.1.7.0
- polysemy-methodology-composite-0.1.4.0
- polysemy-path-0.2.0.0
- polysemy-time-0.1.3.1
- polysemy-video-0.2.0.0
- git: https://github.com/polysemy-research/polysemy-zoo
  commit: 1eed0f83f595cb7f666fc238da041080ea284938
- typerep-map-0.3.3.0
allow-newer: true
nix:
  packages: [zlib, libffi, ffmpeg, pkg-config, icu]
